import { describe, expect, it } from 'vitest'
import {
  DEFAULT_KAPPA,
  MAX_KAPPA,
  MIN_KAPPA,
  buildRelistTargets,
  defaultPriceModelConfig,
  fitPriceCurve,
  netProfit,
  percentile,
  predictPrice,
  theilSenSlope,
  valueListing,
} from './priceModel'
import type { PriceSample } from './priceModel'

const sample = (quality: number, price: number, cleared = false): PriceSample =>
  ({ quality, price, cleared })

/** Prices generated by a known exponent, so the fit has a right answer. */
const syntheticSamples = (kappa: number, scale: number, qualities: number[], cleared = false) =>
  qualities.map((quality) => sample(quality, Math.round(scale * Math.pow(quality, kappa)), cleared))

describe('percentile', () => {
  it('interpolates between neighbours', () => {
    expect(percentile([10, 20, 30, 40], 0.5)).toBe(25)
  })

  it('handles the degenerate cases', () => {
    expect(percentile([], 0.5)).toBe(0)
    expect(percentile([7], 0.9)).toBe(7)
  })
})

describe('theilSenSlope', () => {
  it('recovers the slope of a clean line', () => {
    const points = [0, 1, 2, 3].map((x) => ({ x, y: 3 * x + 5 }))
    expect(theilSenSlope(points)).toBeCloseTo(3)
  })

  it('ignores a wild outlier that would wreck least squares', () => {
    const points = [0, 1, 2, 3, 4, 5].map((x) => ({ x, y: 3 * x + 5 }))
    points.push({ x: 6, y: 900 })
    expect(theilSenSlope(points)).toBeCloseTo(3, 1)
  })

  it('returns null when every point shares an x', () => {
    expect(theilSenSlope([{ x: 1, y: 2 }, { x: 1, y: 5 }])).toBeNull()
  })
})

describe('curve fitting', () => {
  it('recovers a known exponent from clean data', () => {
    const curve = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8, 1.0]))
    expect(curve?.kind).toBe('fitted')
    expect(curve!.kappa).toBeCloseTo(2.5, 1)
  })

  it('still recovers it with a troll listing in the sample', () => {
    const samples = syntheticSamples(2.5, 1_000_000, [0.4, 0.5, 0.6, 0.7, 0.8, 1.0])
    samples.push(sample(0.45, 99_000_000))
    const curve = fitPriceCurve(samples)
    expect(curve!.kappa).toBeCloseTo(2.5, 0)
  })

  it('clamps an implausible exponent into range', () => {
    const steep = fitPriceCurve(syntheticSamples(12, 1_000_000, [0.4, 0.6, 0.8, 1.0]))
    expect(steep!.kappa).toBe(MAX_KAPPA)
    const flat = fitPriceCurve(syntheticSamples(0.1, 1_000_000, [0.4, 0.6, 0.8, 1.0]))
    expect(flat!.kappa).toBe(MIN_KAPPA)
  })

  it('falls back to anchors on exactly three samples', () => {
    const curve = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.7, 1.0]))
    expect(curve?.kind).toBe('anchored')
    expect(curve!.kappa).toBe(DEFAULT_KAPPA)
    expect(curve!.ceiling).toBeGreaterThan(curve!.base)
  })

  it('refuses to value on fewer than three samples', () => {
    expect(fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.5, 1.0]))).toBeNull()
    expect(fitPriceCurve([])).toBeNull()
  })

  it('discards unusable rows before counting', () => {
    expect(fitPriceCurve([
      sample(0.5, 100),
      sample(0.6, 0),
      sample(0, 500),
    ])).toBeNull()
  })
})

describe('confirmed sales outrank open asks', () => {
  const asks = syntheticSamples(2.5, 5_000_000, [0.4, 0.6, 0.8, 1.0], false)
  const sales = syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8], true)

  it('uses asks while confirmed sales are scarce', () => {
    const curve = fitPriceCurve([...asks, sales[0]!])
    expect(curve!.sampleCount).toBe(5)
    expect(curve!.clearedCount).toBe(1)
  })

  it('switches to sales alone once there are three of them', () => {
    const curve = fitPriceCurve([...asks, ...sales])
    expect(curve!.sampleCount).toBe(3)
    expect(curve!.clearedCount).toBe(3)
    // Priced off what cleared, not off the inflated asks.
    expect(predictPrice(curve!, 1)).toBeLessThan(predictPrice(fitPriceCurve(asks)!, 1))
  })
})

describe('predictPrice', () => {
  it('climbs steeply toward the top of the quality range', () => {
    const curve = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8, 1.0]))!
    const lowGain = predictPrice(curve, 0.6) - predictPrice(curve, 0.4)
    const highGain = predictPrice(curve, 1.0) - predictPrice(curve, 0.8)
    expect(highGain).toBeGreaterThan(lowGain)
  })

  it('does not hand a junk roll the price of a good one', () => {
    const curve = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8, 1.0]))!
    expect(predictPrice(curve, 0.2)).toBeLessThan(predictPrice(curve, 1.0) / 5)
  })

  it('keeps an anchored curve inside its anchors', () => {
    const curve = fitPriceCurve([sample(0.3, 100_000), sample(0.6, 300_000), sample(1, 900_000)])!
    expect(predictPrice(curve, 0)).toBeGreaterThanOrEqual(curve.base)
    expect(predictPrice(curve, 1)).toBeLessThanOrEqual(Math.round(curve.ceiling))
  })
})

describe('relist targets', () => {
  it('undercuts the cheapest listing above the buy price', () => {
    const targets = buildRelistTargets(100_000, 260_000, [90_000, 250_000, 400_000])
    expect(targets.quickRelist).toBe(249_999)
  })

  it('never targets below the buy price', () => {
    const targets = buildRelistTargets(500_000, 100_000, [80_000, 90_000])
    expect(targets.fairRelist).toBe(500_000)
    expect(targets.greedyRelist).toBeGreaterThanOrEqual(500_000)
  })

  it('keeps greedy at or above fair', () => {
    for (const fair of [120_000, 300_000, 480_000]) {
      const targets = buildRelistTargets(100_000, fair, [150_000, 200_000, 500_000])
      expect(targets.greedyRelist).toBeGreaterThanOrEqual(targets.fairRelist)
    }
  })
})

describe('net profit is after tax', () => {
  const config = defaultPriceModelConfig()

  it('subtracts the HDV cut from the sale, not from the purchase', () => {
    expect(netProfit(100_000, 200_000, config)).toBe(96_000)
  })

  it('turns a thin spread negative once tax is applied', () => {
    expect(netProfit(100_000, 101_000, config)).toBeLessThan(0)
  })

  it('honours a configured tax rate', () => {
    expect(netProfit(100_000, 200_000, { hdvTaxRate: 0, minMargin: 0.15 })).toBe(100_000)
  })
})

describe('valueListing', () => {
  const curve = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8, 1.0]))!

  it('flags a genuinely cheap max roll as profitable', () => {
    const result = valueListing({ price: 200_000, quality: 1 }, curve, [900_000, 1_100_000])
    expect(result.fairValue).toBeGreaterThan(800_000)
    expect(result.netAtFair).toBeGreaterThan(0)
    expect(result.marginPercent).toBeGreaterThan(100)
  })

  it('does not flag a junk roll priced like a junk roll', () => {
    const junkFair = predictPrice(curve, 0.25)
    const result = valueListing({ price: junkFair, quality: 0.25 }, curve, [junkFair])
    expect(result.netAtFair).toBeLessThanOrEqual(0)
  })

  it('reports a margin of zero for a free item rather than dividing by zero', () => {
    const result = valueListing({ price: 0, quality: 0.5 }, curve, [])
    expect(Number.isFinite(result.marginPercent)).toBe(true)
  })
})

describe('a deal has to beat the market noise, not just the curve', () => {
  it('does not call a listing a hair under the curve a deal', () => {
    const curve = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8, 1.0]))!
    const fair = predictPrice(curve, 0.8)
    const result = valueListing({ price: Math.round(fair * 0.97), quality: 0.8 }, curve, [])
    expect(result.netAtFair).toBeGreaterThan(0)
    expect(result.isDeal).toBe(false)
    expect(result.edgeRatio).toBeLessThan(1)
  })

  it('calls a listing at half the curve a deal', () => {
    const curve = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8, 1.0]))!
    const fair = predictPrice(curve, 0.8)
    const result = valueListing({ price: Math.round(fair * 0.5), quality: 0.8 }, curve, [])
    expect(result.isDeal).toBe(true)
    expect(result.edgeRatio).toBeGreaterThan(1)
  })

  it('demands a bigger discount in a scattered segment than a tight one', () => {
    const tight = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8, 1.0]))!
    const noisy = fitPriceCurve([
      sample(0.4, 60_000),
      sample(0.6, 900_000),
      sample(0.8, 200_000),
      sample(1.0, 2_000_000),
    ])!
    expect(noisy.residualMad).toBeGreaterThan(tight.residualMad)

    const price = Math.round(predictPrice(noisy, 0.8) * 0.7)
    expect(valueListing({ price, quality: 0.8 }, noisy, []).isDeal).toBe(false)
  })

  it('rejects a thin margin even when the curve is quiet', () => {
    const curve = fitPriceCurve(syntheticSamples(2.5, 1_000_000, [0.4, 0.6, 0.8, 1.0]))!
    const fair = predictPrice(curve, 0.8)
    const result = valueListing(
      { price: Math.round(fair * 0.95), quality: 0.8 },
      curve,
      [],
      { hdvTaxRate: 0.02, minMargin: 0.15 },
    )
    expect(result.isDeal).toBe(false)
  })
})

describe('a fair value may not leave the market it was fitted on', () => {
  // The real list: every Cape au Logis on offer sat between these two prices.
  const realMarket = [2749998, 2750000, 3500000, 3500000, 3599999, 3695477, 3700000, 3999999, 4199000, 4299999, 4300000]
  const asks = realMarket.map((price, index) => sample(0.80 + index * 0.02, price))

  it('does not value an item at double the dearest listing', () => {
    // It valued one at 8 058 990 against a market topping out at 4 300 000.
    const curve = fitPriceCurve(asks)!
    for (const quality of [0.5, 1.0, 1.3, 2.0]) {
      expect(predictPrice(curve, quality)).toBeLessThanOrEqual(4300000 * 1.4)
    }
  })

  it('does not value one below half the cheapest either', () => {
    const curve = fitPriceCurve(asks)!
    expect(predictPrice(curve, 0.01)).toBeGreaterThanOrEqual(2749998 * 0.5)
  })

  it('still ranks a better roll above a worse one inside those bounds', () => {
    const curve = fitPriceCurve(asks)!
    expect(predictPrice(curve, 1.1)).toBeGreaterThan(predictPrice(curve, 0.85))
  })

  it('ignores pairs too close in quality to say anything about the slope', () => {
    // Near-identical qualities divide by nearly zero and pin the exponent to
    // its ceiling, which is what produced the runaway valuation.
    const flat = [
      sample(1.000, 3000000),
      sample(1.001, 3100000),
      sample(1.002, 2900000),
      sample(1.003, 3050000),
    ]
    const curve = fitPriceCurve(flat)!
    expect(predictPrice(curve, 1.2)).toBeLessThanOrEqual(3100000 * 1.4)
  })

  it('records the range it was fitted on', () => {
    const curve = fitPriceCurve(asks)!
    expect(curve.sampleMin).toBe(2749998)
    expect(curve.sampleMax).toBe(4300000)
  })
})

describe('the three relist targets are three different bets', () => {
  // The real case: bought at 3 800 000, fair 4 716 061, and greedy came back
  // identical to fair because it was really just "undercut the next listing".
  const peers = [3876666, 3999999, 4199000, 4299999, 4300000]

  it('never reports greedy equal to fair', () => {
    const targets = buildRelistTargets(3800000, 4716061, peers)
    expect(targets.greedyRelist).toBeGreaterThan(targets.fairRelist)
  })

  it('keeps the three in order', () => {
    const targets = buildRelistTargets(3800000, 4716061, peers)
    expect(targets.quickRelist).toBeLessThan(targets.fairRelist)
    expect(targets.fairRelist).toBeLessThan(targets.greedyRelist)
  })

  it('still undercuts the cheapest listing above you for a quick sale', () => {
    expect(buildRelistTargets(3800000, 4716061, peers).quickRelist).toBe(3876665)
  })

  it('aims at the top of the market when fair sits below it', () => {
    const targets = buildRelistTargets(2000000, 2500000, peers)
    expect(targets.greedyRelist).toBeGreaterThanOrEqual(4300000 - 1)
  })

  it('stays sensible when there are no peers at all', () => {
    const targets = buildRelistTargets(1000000, 1500000, [])
    expect(targets.greedyRelist).toBeGreaterThan(targets.fairRelist)
    expect(targets.fairRelist).toBeGreaterThanOrEqual(1500000 - 1)
  })

  it('never asks below what you paid', () => {
    const targets = buildRelistTargets(5000000, 1000000, peers)
    expect(targets.fairRelist).toBeGreaterThanOrEqual(5000000)
    expect(targets.greedyRelist).toBeGreaterThanOrEqual(targets.fairRelist)
  })
})

describe('quick is a fast sale, not an ambitious one', () => {
  it('never asks above fair value', () => {
    // Ten of seventeen listings in a real capture had quick above fair — the
    // worst asked 5 876 664 for something valued at 4 440 373.
    const peers = [3876666, 4079999, 5876665]
    const targets = buildRelistTargets(4000000, 4440373, peers)
    expect(targets.quickRelist).toBeLessThanOrEqual(targets.fairRelist)
  })

  it('still undercuts a peer that sits below fair', () => {
    const targets = buildRelistTargets(3000000, 4500000, [3876666, 4300000])
    expect(targets.quickRelist).toBe(3876665)
  })

  it('keeps the three targets in order on the real data', () => {
    const peers = [3599999, 3650000, 3699999, 3876666, 4000000, 4350000, 4999999, 5876665]
    for (const [buy, fair] of [[3800000, 4716062], [4000000, 4440373], [3650000, 3730295]]) {
      const targets = buildRelistTargets(buy!, fair!, peers)
      expect(targets.quickRelist).toBeLessThanOrEqual(targets.fairRelist)
      expect(targets.fairRelist).toBeLessThanOrEqual(targets.greedyRelist)
    }
  })
})
